# Generated by Django 4.2.23 on 2025-08-30 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('counter', models.PositiveIntegerField(default=0, verbose_name='Views')),
                ('transcript', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('counter', models.PositiveIntegerField(default=0, verbose_name='Views')),
                ('video_url', models.URLField(verbose_name='Video URL')),
                ('subtitles_url', models.URLField(blank=True, null=True, verbose_name='Subtitles URL')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('object_id', models.PositiveIntegerField()),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Position')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Content Type')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_contents', to='app.page', verbose_name='Page')),
            ],
            options={
                'ordering': ['position', 'id'],
                'indexes': [models.Index(fields=['page', 'position'], name='app_pagecon_page_id_a3bc40_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='pagecontent',
            constraint=models.UniqueConstraint(fields=('page', 'content_type', 'object_id'), name='uniq_page_content_object'),
        ),
        migrations.AddConstraint(
            model_name='pagecontent',
            constraint=models.UniqueConstraint(fields=('page', 'position'), name='uniq_page_position_per_page'),
        ),
    ]
